version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: PR Checker
    validate:
      # we check title format because on squash-merge it becomes the merge-commit message
      - do: title
        must_include:
          regex: "^.{0,75}$"
          message: |
            Title should be at most 75 characters long
      - do: title
        must_include:
          regex: '^(feat|fix|refactor|revert|ci|build|docs|chore)(\([\w\d-]+\))?!?: (\S.+[^.?!])$'
          regex_flag: "none"
          message: |
            Title should follow conventional commit format `type(scope): summary`
            - type is one of feat, fix, refactor, revert, ci, build, docs, chore
            - scope is optional (e.g. a ClickUp ticket reference)
            - summary should start with lower case and not end with punctuation
      - do: description
        no_empty:
          enabled: true
          message: |
            Description should not be empty. Provide what, why, and how.
