name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --group dev
    - name: Test with pytest
      run: uv run pytest
